# Generated by Django 3.0.7 on 2020-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default='slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
