# Generated by Django 3.0.7 on 2020-06-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200613_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(default='My Blog', max_length=150),
            preserve_default=False,
        ),
    ]
